<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RootNamespace>UDP_App</RootNamespace>
    <AssemblyName>UDP_App</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Claude\**" />
    <Content Remove="Claude\**" />
    <EmbeddedResource Remove="Claude\**" />
    <None Remove="Claude\**" />
  </ItemGroup>

</Project>
